version: '3.0'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: amongus
       MYSQL_DATABASE: crewmates
       MYSQL_USER: amongus
       MYSQL_PASSWORD: suspicious
   wordpress:
     depends_on:
       - db
     image: wordpress:6.0.2-php8.0-apache
     ports:
       - "56156:8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: amongus
       WORDPRESS_DB_PASSWORD: suspicious
       WORDPRESS_DB_NAME: crewmates
volumes:
    db_data: {}
